name: Web Server Check
on: 
   workflow_dispatch:
   push:
      tags:
         - checkMe*
jobs:
   run-instructor-tests:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
         - run: make build
         - run: java --version
         - run: curl https://autograder.computing.gvsu.edu/webServerTests.tar --output webServerTests.tar
         - run: tar -xf webServerTests.tar
         - run: make test